### ISSUE TITLE
Example code fails to run.

### ISSUE THREAD

**Issue by AngryKittyMeow** [TobySalusky/MonoGameHtml#3]

**Comment by TobySalusky** [comment]
Hi, I didn't get a chance to respond, but noticed you closed this issue—did you manage to get it to run successfully?

**Comment by AngryKittyMeow** [comment]
I did get the examples to run directly from Visual Studio by selecting them in the dropdown, which I should have noticed right away. As for actually getting the monogamehtml to run in a brand new project that references the monogamehtml.dll, no, I couldn't get even a single snippet of html to render. I am however using monogame for android so I think I've come up with a unique work-around for displaying html on-screen by using multiple views.

**Comment by AngryKittyMeow** [comment]
Thank you for your time. To be honest, I'm sure that you have more important things to work on than hand-holding newb programmer through basic stuff, so thanks for taking the time to respond but trust me I'm not worth your time.

**Comment by realcoloride** [comment]
Hello, sorry to necro this post but then does that mean this project is abandoned?
